### ISSUE TITLE
[meta] Documentation

### ISSUE THREAD

**Issue by szledan** [GepardGraphics/gepard#11]
This is the main tracker issue for documentations of Gepard.

We need to add documentation for the following ittems:

- [ ] Public API Doc.
- [ ] Internal API Doc.
- [ ] Source code documentation.

Please use the Doxygen annotations in Gepard source code. (See.: [www.doxygen.org](http://www.stack.nl/~dimitri/doxygen/))

It could be interesting: [Gepard coding-style](https://github.com/GepardGraphics/gepard/wiki/Coding-style).
