### ISSUE TITLE
[canvas2d] Implement path drawing

### ISSUE THREAD

**Issue by kkristof** [GepardGraphics/gepard#15]
Add support of the path object.
- [x] Integrate the public API part with Doxygen documentations. ([version-0.0.1](https://github.com/GepardGraphics/gepard/milestones/version%200.0.1)) #33 
- [x] Add internal types of Path API. ([version-0.0.1](https://github.com/GepardGraphics/gepard/milestones/version%200.0.1)) #33 
- [x] Add internal Path API with Doxygen documentations. ([version-0.0.1](https://github.com/GepardGraphics/gepard/milestones/version%200.0.1)) #33 
- Add `GLES-2.0` support. ([version-0.0.2](https://github.com/GepardGraphics/gepard/milestones/version%200.0.2))
  - [x] _Types_.
  - [x] _Add Segment Approximator_.
  - [x] _Add Trapezoid Tessellator_.
  - [x] _Basic Pipeline for GLES2_.
  - **TODO**(szledan): Finish this part.
- Add `VULKAN` support.
  - [x] _Types_.
  - **TODO**(szledan): Extend this part.
