### ISSUE TITLE
[meta] Add Vulkan suppport

### ISSUE THREAD

**Issue by kkristof** [GepardGraphics/gepard#7]
This is the main tracker issue for the Vulkan related issues.
The following tasks  (please keep it up to date):
- [ ] Investigate the Vulkan API
- [ ] Determine main components
- [ ] Plan the implementation steps

**Comment by kkristof** [comment]
The following functions already supported in the vulkan developer branch:
* fillRect
* putImage
* getImage
Currently the drawImage is in development and the follow up working item is the path elements.

**Comment by kkristof** [comment]
The drawImage implementation is on the master and the transformation is implemented in the vulkan dev branch
