### ISSUE TITLE
[meta] New design of the API

### ISSUE THREAD

**Issue by kkristof** [GepardGraphics/gepard#97]
This issue tracks the state of the API refactoring, which was agreed during the GeCo 2017.
- [ ] Move the existing Gepard API under the new Canvas API
- [ ] Rename the GepardEngine to Gepard
- [ ] Streamline the Gepard API
- [ ] Expose the internal Gepard API
- [ ] Refactor the build system
- [ ] Update the examples to match with the new API
